name: Update formulae & casks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'
jobs:
  update:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update Casks
        run: ruby ./scripts/update_casks.rb
